#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 19 00:25:02 2018

@author: rath772k
"""

import numpy as np

class log_reg:
    
    def fit(self,x,y,lambda_=0):
        self.x = x
        self.y = y
        self.w = np.zeros((np.shape(x)[1],1))
        self.b = [0]
        self.lambda_ = lambda_
        
    def normalize(self,x):
        Mean=np.mean(x,axis=0)
        Std=np.std(x,axis=0)
        return (x-Mean)/Std,Mean,Std
    
    def sigmoid(self,x):
        return 1/(1 + np.exp(-x))
    
    def cost_fn(self):
        hypo = self.sigmoid(self.x.dot(self.w)+self.b)
        reg = self.lambda_/2/np.size(self.y)*np.square(self.x)
        return np.sum(-1 / np.size(self.y) * (np.log(hypo).T.dot(self.y) + np.log(1-hypo).T.dot(1-self.y))+reg)
    
    def grad_descent(self,l_rate,no_of_iter,lambda_=0):
        m=np.size(self.y)
        for i in range(no_of_iter):
            hypo=self.sigmoid(self.x.dot(self.w)+self.b)
            dif=hypo-self.y     
            self.w-=1/m*self.x.T.dot(dif) + lambda_/m*self.w
            self.b-=np.sum(1/m*dif)
        return self.w,self.b
    
    def predict(self,xin):
        return self.sigmoid(np.dot(xin,self.w)+self.b) >= 0.5
    
    def accuracy(self,x_test,y_test):
        acc=np.mean(self.predict(x_test)==y_test)
        return acc*100
import warnings
warnings.filterwarnings("ignore")
dat = np.loadtxt(open("/home/rath772k/.config/spyder-py3/LogisticRegressionData1.txt"),delimiter=',')
np.random.shuffle(dat)
x = dat[:,0:-1]
y = dat[:,-1:]
(a,b)=np.shape(x)
dp = log_reg()
x,Mean,Std = dp.normalize(x)
x_train=x[0:7*a//10,:]
y_train=y[0:7*a//10,:]
x_test=x[7*a//10:a,:]
y_test=y[7*a//10:a,:]
print("Mean = ",Mean)
print("Standard Deviation = ",Std)
dp.fit(x_train,y_train)
weight,bias=dp.grad_descent(0.5,1000)
dp.cost_fn()
print("weights=",weight)
print("bias=",bias)
print (dp.accuracy(x_test,y_test))
from sklearn.linear_model import LogisticRegression
ap=LogisticRegression().fit(x_train,y_train)
res=ap.predict(x_test).reshape(y_test.shape)
acc=np.mean(res==y_test)
print(res)
print(y_test)
print(acc*100) 
